kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-claim-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
